---
- name: Upload configuration templates | Logstash
  template:
    src: "shipper/{{ item.name }}"
    dest: "{{ logstash_config_root }}/conf.d/{{ item.name }}"

  with_items:
    - { name: 'input.conf' }
    - { name: 'output.conf' }
  when: logstash_shipper

- name: Upload configuration templates | Logstash
  template:
    src: "aggregator/{{ item.name }}"
    dest: "{{ logstash_config_root }}/conf.d/{{ item.name }}"

  with_items:
    - { name: 'input.conf' }
    - { name: 'output.conf' }
  when: logstash_aggregator

- name: Upload configuration templates | Logstash
  template:
    src: "indexer/{{ item.name }}"
    dest: "{{ logstash_config_root }}/conf.d/{{ item.name }}"

  with_items:
    - { name: 'input.conf' }
    - { name: 'output.conf' }
  when: logstash_indexer

- name: Add Filter for overly large messages | Logstash
  template:
    src: "shipper/filter.conf"
    dest: "{{ logstash_config_root }}/conf.d/filter.conf"
  when: logstash_shipper_remove_large_events
