---
- name: Upload configuration templates | Logstash
  template:
    src: "shipper/{{ item.name }}"
    dest: "{{ logstash_config_root }}/conf.d/{{ item.name }}"

  with_items:
    - { name: 'input.conf' }
    - { name: 'output.conf' }
  when: logstash_shipper

- name: Upload configuration templates | Logstash
  template:
    src: "broker/{{ item.name }}"
    dest: "{{ logstash_config_root }}/conf.d/{{ item.name }}"

  with_items:
    - { name: 'input.conf' }
    - { name: 'output.conf' }
  when: logstash_aggregator

- name: Upload configuration templates | Logstash
  template:
    src: "indexer/{{ item.name }}"
    dest: "{{ logstash_config_root }}/conf.d/{{ item.name }}"

  with_items:
    - { name: 'input.conf' }
    - { name: 'output.conf' }
  when: logstash_indexer
