---
- name: Upload configuration templates | Logstash
  template:
    src: "shipper/{{ item.name }}"
    dest: "{{ logstash_config_root }}/conf.d/{{ item.name }}"

  with_items:
    - { name: 'input.conf' }
    - { name: 'output.conf' }
  when: logstash_shipper
  tags:
    - logstash

- name: Upload configuration templates | Logstash
  template:
    src: "aggregator/{{ item.name }}"
    dest: "{{ logstash_config_root }}/conf.d/{{ item.name }}"

  with_items:
    - { name: 'input.conf' }
    - { name: 'output.conf' }
  when: logstash_aggregator
  tags:
    - logstash

- name: Upload configuration templates | Logstash
  template:
    src: "indexer/{{ item.name }}"
    dest: "{{ logstash_config_root }}/conf.d/{{ item.name }}"

  with_items:
    - { name: 'input.conf' }
    - { name: 'output.conf' }
  when: logstash_indexer
  tags:
    - logstash

- name: Add Filter for overly large messages | Logstash
  template:
    src: "shipper/filter.conf"
    dest: "{{ logstash_config_root }}/conf.d/filter.conf"
  when: logstash_shipper_remove_large_events
  tags:
    - logstash

#- name: Upload default logstash template
#  template:
#    src: "etc/default/logstash"
#    dest: "/etc/default/logstash"
#  tags:
#    - logstash
- name: Upload logrotate from elastic/logstash as template
  template:
    src: "etc/logrotate.d/logstash"
    dest: "/etc/logrotate.d/logstash"
  tags:
    - logstash

