---
- name: Import Signing Key | Elasticsearch.org
  apt_key:
    state: present
    url: "http://packages.elasticsearch.org/GPG-KEY-elasticsearch"

- name: Import Repository | Logstash
  apt_repository:
    state: present
    repo: 'deb http://packages.elasticsearch.org/logstash/1.4/debian stable main'
  notify: Update Package Cache

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - logstash
