---
- name: Install Packages | apt
  apt:
    state: latest
    name: "{{ item }}"
  with_items:
    - logstash

- name: Install Plugin | log-courier
  command: "{{ item }}"
  with_items:
    - /opt/logstash/bin/plugin install logstash-input-courier
    - /opt/logstash/bin/plugin install logstash-output-courier
