---
- name: "Directory Exists | {{ logstash_log_root }}"
  file:
    state: directory
    path: "{{ logstash_log_root }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0775
  tags:
    - directory-structure
    - logging
    - logstash
  with_items:
    - "{{ logstash_log_root }}"
    - "{{ logstash_config_root }}/conf.d"
