---
- name: "Directory Exists | {{ logstash_log_root }}"
  file:
    state: directory
    path: "{{ logstash_log_root }}"
    owner: "{{ logstash_user }}"
    group: "{{ logstash_group }}"
    mode: 0775
  tags:
    - directory-structure
    - logging
    - logstash

- name: Configure | logstash | logfile
  lineinfile:
    state: present
    dest: /etc/init/logstash.conf
    regexp: '^  LS_LOG_FILE'
    line: "  LS_LOG_FILE={{ logstash_log_path }}"
  notify: Reload Service | logstash
  tags:
    - configuration
    - precise-configuration
    - logging
    - logstash
