---
- name: Configure | logstash | logfile
  lineinfile:
    state: present
    dest: /etc/init/logstash.conf
    regexp: '^  LS_LOG_FILE'
    line: "  LS_LOG_FILE={{ logstash_log_path }}"
  notify: Reload Service | logstash
  tags:
    - configuration
    - precise-configuration
    - logging
    - logstash
