---
- name: Upload Config | monit | logstash
  template:
    src: etc/monit/conf.d/logstash
    dest: /etc/monit/conf.d/logstash
  notify: Reload Service | monit

- name: Trigger All Callbacks
  meta: flush_handlers
